#pragma once

#include "Object.h"
#include "DeskObject.h"
#include "BoxObject.h"
#include "MrRudis.h"
#include "SchoolBoyA.h"
#include "SchoolBoyB.h"
#include "SchoolBoyE.h"
#include "SchoolGirlA.h"
#include "SchoolGirlB.h"
#include "SchoolGirlE.h"
#include "WorkingFemaleA.h"
#include "WorkingMaleD.h"
#include "TableObject.h"
#include "DeskChairObject.h"
#include "TeacherTable.h"